// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "movement.proto" (package "movement", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MovementService } from "./movement";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { MovementUpdate } from "./movement";
import type { WatchMovementsRequest } from "./movement";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service movement.MovementService
 */
export interface IMovementServiceClient {
    /**
     * @generated from protobuf rpc: WatchMovements
     */
    watchMovements(input: WatchMovementsRequest, options?: RpcOptions): ServerStreamingCall<WatchMovementsRequest, MovementUpdate>;
}
/**
 * @generated from protobuf service movement.MovementService
 */
export class MovementServiceClient implements IMovementServiceClient, ServiceInfo {
    typeName = MovementService.typeName;
    methods = MovementService.methods;
    options = MovementService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: WatchMovements
     */
    watchMovements(input: WatchMovementsRequest, options?: RpcOptions): ServerStreamingCall<WatchMovementsRequest, MovementUpdate> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchMovementsRequest, MovementUpdate>("serverStreaming", this._transport, method, opt, input);
    }
}
