// @generated by protobuf-ts 2.11.1 with parameter client_grpc1,generate_dependencies
// @generated from protobuf file "movement.proto" (package "movement", syntax proto3)
// tslint:disable
import { MovementService } from "./movement";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { MovementUpdate } from "./movement";
import type { WatchMovementsRequest } from "./movement";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service movement.MovementService
 */
export interface IMovementServiceClient {
    /**
     * @generated from protobuf rpc: WatchMovements
     */
    watchMovements(input: WatchMovementsRequest, metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<MovementUpdate>;
    watchMovements(input: WatchMovementsRequest, options?: grpc.CallOptions): grpc.ClientReadableStream<MovementUpdate>;
}
/**
 * @generated from protobuf service movement.MovementService
 */
export class MovementServiceClient extends grpc.Client implements IMovementServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: WatchMovements
     */
    watchMovements(input: WatchMovementsRequest, metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientReadableStream<MovementUpdate> {
        const method = MovementService.methods[0];
        return this.makeServerStreamRequest<WatchMovementsRequest, MovementUpdate>(`/${MovementService.typeName}/${method.name}`, (value: WatchMovementsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): MovementUpdate => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), options);
    }
}
