// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/product/product.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_WatchStockAlerts_FullMethodName        = "/product.ProductService/WatchStockAlerts"
	ProductService_WatchTopProductsByPrice_FullMethodName = "/product.ProductService/WatchTopProductsByPrice"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	WatchStockAlerts(ctx context.Context, in *WatchStockAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockAlertUpdate], error)
	WatchTopProductsByPrice(ctx context.Context, in *WatchTopProductsByPriceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceUpdate], error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) WatchStockAlerts(ctx context.Context, in *WatchStockAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockAlertUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[0], ProductService_WatchStockAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStockAlertsRequest, StockAlertUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_WatchStockAlertsClient = grpc.ServerStreamingClient[StockAlertUpdate]

func (c *productServiceClient) WatchTopProductsByPrice(ctx context.Context, in *WatchTopProductsByPriceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[1], ProductService_WatchTopProductsByPrice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTopProductsByPriceRequest, PriceUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_WatchTopProductsByPriceClient = grpc.ServerStreamingClient[PriceUpdate]

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	WatchStockAlerts(*WatchStockAlertsRequest, grpc.ServerStreamingServer[StockAlertUpdate]) error
	WatchTopProductsByPrice(*WatchTopProductsByPriceRequest, grpc.ServerStreamingServer[PriceUpdate]) error
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) WatchStockAlerts(*WatchStockAlertsRequest, grpc.ServerStreamingServer[StockAlertUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchStockAlerts not implemented")
}
func (UnimplementedProductServiceServer) WatchTopProductsByPrice(*WatchTopProductsByPriceRequest, grpc.ServerStreamingServer[PriceUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchTopProductsByPrice not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_WatchStockAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStockAlertsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).WatchStockAlerts(m, &grpc.GenericServerStream[WatchStockAlertsRequest, StockAlertUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_WatchStockAlertsServer = grpc.ServerStreamingServer[StockAlertUpdate]

func _ProductService_WatchTopProductsByPrice_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTopProductsByPriceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).WatchTopProductsByPrice(m, &grpc.GenericServerStream[WatchTopProductsByPriceRequest, PriceUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_WatchTopProductsByPriceServer = grpc.ServerStreamingServer[PriceUpdate]

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStockAlerts",
			Handler:       _ProductService_WatchStockAlerts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTopProductsByPrice",
			Handler:       _ProductService_WatchTopProductsByPrice_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/product/product.proto",
}
