// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price             int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock             int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	LowStockThreshold int32                  `protobuf:"varint,6,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	Sku               string                 `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode           string                 `protobuf:"bytes,8,opt,name=barcode,proto3" json:"barcode,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetLowStockThreshold() int32 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type StockAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   string                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	ProductTitle  string                 `protobuf:"bytes,2,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	CurrentStock  int32                  `protobuf:"varint,3,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`
	Threshold     int32                  `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	AlertType     string                 `protobuf:"bytes,5,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // "low_stock" or "out_of_stock"
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAlert) Reset() {
	*x = StockAlert{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAlert) ProtoMessage() {}

func (x *StockAlert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAlert.ProtoReflect.Descriptor instead.
func (*StockAlert) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *StockAlert) GetProductUuid() string {
	if x != nil {
		return x.ProductUuid
	}
	return ""
}

func (x *StockAlert) GetProductTitle() string {
	if x != nil {
		return x.ProductTitle
	}
	return ""
}

func (x *StockAlert) GetCurrentStock() int32 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

func (x *StockAlert) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StockAlert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *StockAlert) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *PriceUpdate) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *PriceUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type WatchStockAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStockAlertsRequest) Reset() {
	*x = WatchStockAlertsRequest{}
	mi := &file_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStockAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStockAlertsRequest) ProtoMessage() {}

func (x *WatchStockAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStockAlertsRequest.ProtoReflect.Descriptor instead.
func (*WatchStockAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{3}
}

type StockAlertUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*StockAlert          `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAlertUpdate) Reset() {
	*x = StockAlertUpdate{}
	mi := &file_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAlertUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAlertUpdate) ProtoMessage() {}

func (x *StockAlertUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAlertUpdate.ProtoReflect.Descriptor instead.
func (*StockAlertUpdate) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *StockAlertUpdate) GetAlerts() []*StockAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *StockAlertUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type WatchTopProductsByPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 0 means no limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTopProductsByPriceRequest) Reset() {
	*x = WatchTopProductsByPriceRequest{}
	mi := &file_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTopProductsByPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTopProductsByPriceRequest) ProtoMessage() {}

func (x *WatchTopProductsByPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTopProductsByPriceRequest.ProtoReflect.Descriptor instead.
func (*WatchTopProductsByPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *WatchTopProductsByPriceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\aproduct\"\x9b\x02\n" +
	"\aProduct\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12.\n" +
	"\x13low_stock_threshold\x18\x06 \x01(\x05R\x11lowStockThreshold\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\b \x01(\tR\abarcode\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xd4\x01\n" +
	"\n" +
	"StockAlert\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\tR\vproductUuid\x12#\n" +
	"\rproduct_title\x18\x02 \x01(\tR\fproductTitle\x12#\n" +
	"\rcurrent_stock\x18\x03 \x01(\x05R\fcurrentStock\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x05R\tthreshold\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x05 \x01(\tR\talertType\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"Y\n" +
	"\vPriceUpdate\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\x19\n" +
	"\x17WatchStockAlertsRequest\"]\n" +
	"\x10StockAlertUpdate\x12+\n" +
	"\x06alerts\x18\x01 \x03(\v2\x13.product.StockAlertR\x06alerts\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"6\n" +
	"\x1eWatchTopProductsByPriceRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit2\xbf\x01\n" +
	"\x0eProductService\x12Q\n" +
	"\x10WatchStockAlerts\x12 .product.WatchStockAlertsRequest\x1a\x19.product.StockAlertUpdate0\x01\x12Z\n" +
	"\x17WatchTopProductsByPrice\x12'.product.WatchTopProductsByPriceRequest\x1a\x14.product.PriceUpdate0\x01B\x0fZ\rproto/productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_product_product_proto_goTypes = []any{
	(*Product)(nil),                        // 0: product.Product
	(*StockAlert)(nil),                     // 1: product.StockAlert
	(*PriceUpdate)(nil),                    // 2: product.PriceUpdate
	(*WatchStockAlertsRequest)(nil),        // 3: product.WatchStockAlertsRequest
	(*StockAlertUpdate)(nil),               // 4: product.StockAlertUpdate
	(*WatchTopProductsByPriceRequest)(nil), // 5: product.WatchTopProductsByPriceRequest
}
var file_proto_product_product_proto_depIdxs = []int32{
	0, // 0: product.PriceUpdate.products:type_name -> product.Product
	1, // 1: product.StockAlertUpdate.alerts:type_name -> product.StockAlert
	3, // 2: product.ProductService.WatchStockAlerts:input_type -> product.WatchStockAlertsRequest
	5, // 3: product.ProductService.WatchTopProductsByPrice:input_type -> product.WatchTopProductsByPriceRequest
	4, // 4: product.ProductService.WatchStockAlerts:output_type -> product.StockAlertUpdate
	2, // 5: product.ProductService.WatchTopProductsByPrice:output_type -> product.PriceUpdate
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
