// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/movement/movement.proto

package movement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_movement_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movement_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_movement_movement_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_proto_movement_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movement_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_proto_movement_movement_proto_rawDescGZIP(), []int{1}
}

func (x *Warehouse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StockMovement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProductUuid      string                 `protobuf:"bytes,2,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	WarehouseUuid    string                 `protobuf:"bytes,3,opt,name=warehouse_uuid,json=warehouseUuid,proto3" json:"warehouse_uuid,omitempty"`
	Product          *Product               `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	Warehouse        *Warehouse             `protobuf:"bytes,5,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	MovementType     string                 `protobuf:"bytes,6,opt,name=movement_type,json=movementType,proto3" json:"movement_type,omitempty"` // STOCK_IN, STOCK_OUT, TRANSFER, ADJUSTMENT
	Quantity         int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PreviousQty      int32                  `protobuf:"varint,8,opt,name=previous_qty,json=previousQty,proto3" json:"previous_qty,omitempty"`
	NewQty           int32                  `protobuf:"varint,9,opt,name=new_qty,json=newQty,proto3" json:"new_qty,omitempty"`
	ReferenceNumber  string                 `protobuf:"bytes,10,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ToWarehouseUuid  string                 `protobuf:"bytes,11,opt,name=to_warehouse_uuid,json=toWarehouseUuid,proto3" json:"to_warehouse_uuid,omitempty"`
	AdjustmentReason string                 `protobuf:"bytes,12,opt,name=adjustment_reason,json=adjustmentReason,proto3" json:"adjustment_reason,omitempty"`
	Notes            string                 `protobuf:"bytes,13,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,14,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	MovementDate     string                 `protobuf:"bytes,15,opt,name=movement_date,json=movementDate,proto3" json:"movement_date,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StockMovement) Reset() {
	*x = StockMovement{}
	mi := &file_proto_movement_movement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockMovement) ProtoMessage() {}

func (x *StockMovement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movement_movement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockMovement.ProtoReflect.Descriptor instead.
func (*StockMovement) Descriptor() ([]byte, []int) {
	return file_proto_movement_movement_proto_rawDescGZIP(), []int{2}
}

func (x *StockMovement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StockMovement) GetProductUuid() string {
	if x != nil {
		return x.ProductUuid
	}
	return ""
}

func (x *StockMovement) GetWarehouseUuid() string {
	if x != nil {
		return x.WarehouseUuid
	}
	return ""
}

func (x *StockMovement) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *StockMovement) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

func (x *StockMovement) GetMovementType() string {
	if x != nil {
		return x.MovementType
	}
	return ""
}

func (x *StockMovement) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockMovement) GetPreviousQty() int32 {
	if x != nil {
		return x.PreviousQty
	}
	return 0
}

func (x *StockMovement) GetNewQty() int32 {
	if x != nil {
		return x.NewQty
	}
	return 0
}

func (x *StockMovement) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *StockMovement) GetToWarehouseUuid() string {
	if x != nil {
		return x.ToWarehouseUuid
	}
	return ""
}

func (x *StockMovement) GetAdjustmentReason() string {
	if x != nil {
		return x.AdjustmentReason
	}
	return ""
}

func (x *StockMovement) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StockMovement) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *StockMovement) GetMovementDate() string {
	if x != nil {
		return x.MovementDate
	}
	return ""
}

func (x *StockMovement) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StockMovement) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WatchMovementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 0 means no limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMovementsRequest) Reset() {
	*x = WatchMovementsRequest{}
	mi := &file_proto_movement_movement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMovementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMovementsRequest) ProtoMessage() {}

func (x *WatchMovementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movement_movement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMovementsRequest.ProtoReflect.Descriptor instead.
func (*WatchMovementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_movement_movement_proto_rawDescGZIP(), []int{3}
}

func (x *WatchMovementsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MovementUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movements     []*StockMovement       `protobuf:"bytes,1,rep,name=movements,proto3" json:"movements,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementUpdate) Reset() {
	*x = MovementUpdate{}
	mi := &file_proto_movement_movement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementUpdate) ProtoMessage() {}

func (x *MovementUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movement_movement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementUpdate.ProtoReflect.Descriptor instead.
func (*MovementUpdate) Descriptor() ([]byte, []int) {
	return file_proto_movement_movement_proto_rawDescGZIP(), []int{4}
}

func (x *MovementUpdate) GetMovements() []*StockMovement {
	if x != nil {
		return x.Movements
	}
	return nil
}

func (x *MovementUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_movement_movement_proto protoreflect.FileDescriptor

const file_proto_movement_movement_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/movement/movement.proto\x12\bmovement\"3\n" +
	"\aProduct\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"3\n" +
	"\tWarehouse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe6\x04\n" +
	"\rStockMovement\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fproduct_uuid\x18\x02 \x01(\tR\vproductUuid\x12%\n" +
	"\x0ewarehouse_uuid\x18\x03 \x01(\tR\rwarehouseUuid\x12+\n" +
	"\aproduct\x18\x04 \x01(\v2\x11.movement.ProductR\aproduct\x121\n" +
	"\twarehouse\x18\x05 \x01(\v2\x13.movement.WarehouseR\twarehouse\x12#\n" +
	"\rmovement_type\x18\x06 \x01(\tR\fmovementType\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12!\n" +
	"\fprevious_qty\x18\b \x01(\x05R\vpreviousQty\x12\x17\n" +
	"\anew_qty\x18\t \x01(\x05R\x06newQty\x12)\n" +
	"\x10reference_number\x18\n" +
	" \x01(\tR\x0freferenceNumber\x12*\n" +
	"\x11to_warehouse_uuid\x18\v \x01(\tR\x0ftoWarehouseUuid\x12+\n" +
	"\x11adjustment_reason\x18\f \x01(\tR\x10adjustmentReason\x12\x14\n" +
	"\x05notes\x18\r \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_by\x18\x0e \x01(\tR\tcreatedBy\x12#\n" +
	"\rmovement_date\x18\x0f \x01(\tR\fmovementDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\"-\n" +
	"\x15WatchMovementsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"e\n" +
	"\x0eMovementUpdate\x125\n" +
	"\tmovements\x18\x01 \x03(\v2\x17.movement.StockMovementR\tmovements\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp2`\n" +
	"\x0fMovementService\x12M\n" +
	"\x0eWatchMovements\x12\x1f.movement.WatchMovementsRequest\x1a\x18.movement.MovementUpdate0\x01B\x10Z\x0eproto/movementb\x06proto3"

var (
	file_proto_movement_movement_proto_rawDescOnce sync.Once
	file_proto_movement_movement_proto_rawDescData []byte
)

func file_proto_movement_movement_proto_rawDescGZIP() []byte {
	file_proto_movement_movement_proto_rawDescOnce.Do(func() {
		file_proto_movement_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_movement_movement_proto_rawDesc), len(file_proto_movement_movement_proto_rawDesc)))
	})
	return file_proto_movement_movement_proto_rawDescData
}

var file_proto_movement_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_movement_movement_proto_goTypes = []any{
	(*Product)(nil),               // 0: movement.Product
	(*Warehouse)(nil),             // 1: movement.Warehouse
	(*StockMovement)(nil),         // 2: movement.StockMovement
	(*WatchMovementsRequest)(nil), // 3: movement.WatchMovementsRequest
	(*MovementUpdate)(nil),        // 4: movement.MovementUpdate
}
var file_proto_movement_movement_proto_depIdxs = []int32{
	0, // 0: movement.StockMovement.product:type_name -> movement.Product
	1, // 1: movement.StockMovement.warehouse:type_name -> movement.Warehouse
	2, // 2: movement.MovementUpdate.movements:type_name -> movement.StockMovement
	3, // 3: movement.MovementService.WatchMovements:input_type -> movement.WatchMovementsRequest
	4, // 4: movement.MovementService.WatchMovements:output_type -> movement.MovementUpdate
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_movement_movement_proto_init() }
func file_proto_movement_movement_proto_init() {
	if File_proto_movement_movement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_movement_movement_proto_rawDesc), len(file_proto_movement_movement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_movement_movement_proto_goTypes,
		DependencyIndexes: file_proto_movement_movement_proto_depIdxs,
		MessageInfos:      file_proto_movement_movement_proto_msgTypes,
	}.Build()
	File_proto_movement_movement_proto = out.File
	file_proto_movement_movement_proto_goTypes = nil
	file_proto_movement_movement_proto_depIdxs = nil
}
