// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/movement/movement.proto

package movement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovementService_WatchMovements_FullMethodName = "/movement.MovementService/WatchMovements"
)

// MovementServiceClient is the client API for MovementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovementServiceClient interface {
	WatchMovements(ctx context.Context, in *WatchMovementsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MovementUpdate], error)
}

type movementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovementServiceClient(cc grpc.ClientConnInterface) MovementServiceClient {
	return &movementServiceClient{cc}
}

func (c *movementServiceClient) WatchMovements(ctx context.Context, in *WatchMovementsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MovementUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MovementService_ServiceDesc.Streams[0], MovementService_WatchMovements_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMovementsRequest, MovementUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MovementService_WatchMovementsClient = grpc.ServerStreamingClient[MovementUpdate]

// MovementServiceServer is the server API for MovementService service.
// All implementations must embed UnimplementedMovementServiceServer
// for forward compatibility.
type MovementServiceServer interface {
	WatchMovements(*WatchMovementsRequest, grpc.ServerStreamingServer[MovementUpdate]) error
	mustEmbedUnimplementedMovementServiceServer()
}

// UnimplementedMovementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovementServiceServer struct{}

func (UnimplementedMovementServiceServer) WatchMovements(*WatchMovementsRequest, grpc.ServerStreamingServer[MovementUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchMovements not implemented")
}
func (UnimplementedMovementServiceServer) mustEmbedUnimplementedMovementServiceServer() {}
func (UnimplementedMovementServiceServer) testEmbeddedByValue()                         {}

// UnsafeMovementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovementServiceServer will
// result in compilation errors.
type UnsafeMovementServiceServer interface {
	mustEmbedUnimplementedMovementServiceServer()
}

func RegisterMovementServiceServer(s grpc.ServiceRegistrar, srv MovementServiceServer) {
	// If the following call panics, it indicates UnimplementedMovementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovementService_ServiceDesc, srv)
}

func _MovementService_WatchMovements_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMovementsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MovementServiceServer).WatchMovements(m, &grpc.GenericServerStream[WatchMovementsRequest, MovementUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MovementService_WatchMovementsServer = grpc.ServerStreamingServer[MovementUpdate]

// MovementService_ServiceDesc is the grpc.ServiceDesc for MovementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movement.MovementService",
	HandlerType: (*MovementServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMovements",
			Handler:       _MovementService_WatchMovements_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/movement/movement.proto",
}
