// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "product.proto" (package "product", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProductService } from "./product";
import type { PriceUpdate } from "./product";
import type { WatchTopProductsByPriceRequest } from "./product";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { StockAlertUpdate } from "./product";
import type { WatchStockAlertsRequest } from "./product";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service product.ProductService
 */
export interface IProductServiceClient {
    /**
     * @generated from protobuf rpc: WatchStockAlerts
     */
    watchStockAlerts(input: WatchStockAlertsRequest, options?: RpcOptions): ServerStreamingCall<WatchStockAlertsRequest, StockAlertUpdate>;
    /**
     * @generated from protobuf rpc: WatchTopProductsByPrice
     */
    watchTopProductsByPrice(input: WatchTopProductsByPriceRequest, options?: RpcOptions): ServerStreamingCall<WatchTopProductsByPriceRequest, PriceUpdate>;
}
/**
 * @generated from protobuf service product.ProductService
 */
export class ProductServiceClient implements IProductServiceClient, ServiceInfo {
    typeName = ProductService.typeName;
    methods = ProductService.methods;
    options = ProductService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: WatchStockAlerts
     */
    watchStockAlerts(input: WatchStockAlertsRequest, options?: RpcOptions): ServerStreamingCall<WatchStockAlertsRequest, StockAlertUpdate> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchStockAlertsRequest, StockAlertUpdate>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WatchTopProductsByPrice
     */
    watchTopProductsByPrice(input: WatchTopProductsByPriceRequest, options?: RpcOptions): ServerStreamingCall<WatchTopProductsByPriceRequest, PriceUpdate> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchTopProductsByPriceRequest, PriceUpdate>("serverStreaming", this._transport, method, opt, input);
    }
}
