// @generated by protobuf-ts 2.11.1 with parameter client_grpc1,generate_dependencies
// @generated from protobuf file "product.proto" (package "product", syntax proto3)
// tslint:disable
import { ProductService } from "./product";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { PriceUpdate } from "./product";
import type { WatchTopProductsByPriceRequest } from "./product";
import type { StockAlertUpdate } from "./product";
import type { WatchStockAlertsRequest } from "./product";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service product.ProductService
 */
export interface IProductServiceClient {
    /**
     * @generated from protobuf rpc: WatchStockAlerts
     */
    watchStockAlerts(input: WatchStockAlertsRequest, metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<StockAlertUpdate>;
    watchStockAlerts(input: WatchStockAlertsRequest, options?: grpc.CallOptions): grpc.ClientReadableStream<StockAlertUpdate>;
    /**
     * @generated from protobuf rpc: WatchTopProductsByPrice
     */
    watchTopProductsByPrice(input: WatchTopProductsByPriceRequest, metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<PriceUpdate>;
    watchTopProductsByPrice(input: WatchTopProductsByPriceRequest, options?: grpc.CallOptions): grpc.ClientReadableStream<PriceUpdate>;
}
/**
 * @generated from protobuf service product.ProductService
 */
export class ProductServiceClient extends grpc.Client implements IProductServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: WatchStockAlerts
     */
    watchStockAlerts(input: WatchStockAlertsRequest, metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientReadableStream<StockAlertUpdate> {
        const method = ProductService.methods[0];
        return this.makeServerStreamRequest<WatchStockAlertsRequest, StockAlertUpdate>(`/${ProductService.typeName}/${method.name}`, (value: WatchStockAlertsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): StockAlertUpdate => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), options);
    }
    /**
     * @generated from protobuf rpc: WatchTopProductsByPrice
     */
    watchTopProductsByPrice(input: WatchTopProductsByPriceRequest, metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientReadableStream<PriceUpdate> {
        const method = ProductService.methods[1];
        return this.makeServerStreamRequest<WatchTopProductsByPriceRequest, PriceUpdate>(`/${ProductService.typeName}/${method.name}`, (value: WatchTopProductsByPriceRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): PriceUpdate => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), options);
    }
}
