// @generated by protobuf-ts 2.11.1 with parameter client_grpc1,generate_dependencies
// @generated from protobuf file "product.proto" (package "product", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message product.Product
 */
export interface Product {
    /**
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: int32 price = 4
     */
    price: number;
    /**
     * @generated from protobuf field: int32 stock = 5
     */
    stock: number;
    /**
     * @generated from protobuf field: int32 low_stock_threshold = 6
     */
    lowStockThreshold: number;
    /**
     * @generated from protobuf field: string sku = 7
     */
    sku: string;
    /**
     * @generated from protobuf field: string barcode = 8
     */
    barcode: string;
    /**
     * @generated from protobuf field: string updated_at = 9
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: string created_at = 10
     */
    createdAt: string;
}
/**
 * @generated from protobuf message product.StockAlert
 */
export interface StockAlert {
    /**
     * @generated from protobuf field: string product_uuid = 1
     */
    productUuid: string;
    /**
     * @generated from protobuf field: string product_title = 2
     */
    productTitle: string;
    /**
     * @generated from protobuf field: int32 current_stock = 3
     */
    currentStock: number;
    /**
     * @generated from protobuf field: int32 threshold = 4
     */
    threshold: number;
    /**
     * @generated from protobuf field: string alert_type = 5
     */
    alertType: string; // "low_stock" or "out_of_stock"
    /**
     * @generated from protobuf field: string timestamp = 6
     */
    timestamp: string;
}
/**
 * @generated from protobuf message product.PriceUpdate
 */
export interface PriceUpdate {
    /**
     * @generated from protobuf field: repeated product.Product products = 1
     */
    products: Product[];
    /**
     * @generated from protobuf field: string timestamp = 2
     */
    timestamp: string;
}
/**
 * @generated from protobuf message product.WatchStockAlertsRequest
 */
export interface WatchStockAlertsRequest {
}
/**
 * @generated from protobuf message product.StockAlertUpdate
 */
export interface StockAlertUpdate {
    /**
     * @generated from protobuf field: repeated product.StockAlert alerts = 1
     */
    alerts: StockAlert[];
    /**
     * @generated from protobuf field: string timestamp = 2
     */
    timestamp: string;
}
/**
 * @generated from protobuf message product.WatchTopProductsByPriceRequest
 */
export interface WatchTopProductsByPriceRequest {
    /**
     * @generated from protobuf field: int32 limit = 1
     */
    limit: number; // 0 means no limit
}
// @generated message type with reflection information, may provide speed optimized methods
class Product$Type extends MessageType<Product> {
    constructor() {
        super("product.Product", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "price", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "stock", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "low_stock_threshold", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "sku", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "barcode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Product>): Product {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.title = "";
        message.description = "";
        message.price = 0;
        message.stock = 0;
        message.lowStockThreshold = 0;
        message.sku = "";
        message.barcode = "";
        message.updatedAt = "";
        message.createdAt = "";
        if (value !== undefined)
            reflectionMergePartial<Product>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Product): Product {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* int32 price */ 4:
                    message.price = reader.int32();
                    break;
                case /* int32 stock */ 5:
                    message.stock = reader.int32();
                    break;
                case /* int32 low_stock_threshold */ 6:
                    message.lowStockThreshold = reader.int32();
                    break;
                case /* string sku */ 7:
                    message.sku = reader.string();
                    break;
                case /* string barcode */ 8:
                    message.barcode = reader.string();
                    break;
                case /* string updated_at */ 9:
                    message.updatedAt = reader.string();
                    break;
                case /* string created_at */ 10:
                    message.createdAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Product, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* int32 price = 4; */
        if (message.price !== 0)
            writer.tag(4, WireType.Varint).int32(message.price);
        /* int32 stock = 5; */
        if (message.stock !== 0)
            writer.tag(5, WireType.Varint).int32(message.stock);
        /* int32 low_stock_threshold = 6; */
        if (message.lowStockThreshold !== 0)
            writer.tag(6, WireType.Varint).int32(message.lowStockThreshold);
        /* string sku = 7; */
        if (message.sku !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.sku);
        /* string barcode = 8; */
        if (message.barcode !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.barcode);
        /* string updated_at = 9; */
        if (message.updatedAt !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.updatedAt);
        /* string created_at = 10; */
        if (message.createdAt !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.createdAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.Product
 */
export const Product = new Product$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StockAlert$Type extends MessageType<StockAlert> {
    constructor() {
        super("product.StockAlert", [
            { no: 1, name: "product_uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "product_title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "current_stock", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "threshold", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "alert_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StockAlert>): StockAlert {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.productUuid = "";
        message.productTitle = "";
        message.currentStock = 0;
        message.threshold = 0;
        message.alertType = "";
        message.timestamp = "";
        if (value !== undefined)
            reflectionMergePartial<StockAlert>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StockAlert): StockAlert {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string product_uuid */ 1:
                    message.productUuid = reader.string();
                    break;
                case /* string product_title */ 2:
                    message.productTitle = reader.string();
                    break;
                case /* int32 current_stock */ 3:
                    message.currentStock = reader.int32();
                    break;
                case /* int32 threshold */ 4:
                    message.threshold = reader.int32();
                    break;
                case /* string alert_type */ 5:
                    message.alertType = reader.string();
                    break;
                case /* string timestamp */ 6:
                    message.timestamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StockAlert, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string product_uuid = 1; */
        if (message.productUuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.productUuid);
        /* string product_title = 2; */
        if (message.productTitle !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.productTitle);
        /* int32 current_stock = 3; */
        if (message.currentStock !== 0)
            writer.tag(3, WireType.Varint).int32(message.currentStock);
        /* int32 threshold = 4; */
        if (message.threshold !== 0)
            writer.tag(4, WireType.Varint).int32(message.threshold);
        /* string alert_type = 5; */
        if (message.alertType !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.alertType);
        /* string timestamp = 6; */
        if (message.timestamp !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.StockAlert
 */
export const StockAlert = new StockAlert$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PriceUpdate$Type extends MessageType<PriceUpdate> {
    constructor() {
        super("product.PriceUpdate", [
            { no: 1, name: "products", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Product },
            { no: 2, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PriceUpdate>): PriceUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.products = [];
        message.timestamp = "";
        if (value !== undefined)
            reflectionMergePartial<PriceUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PriceUpdate): PriceUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated product.Product products */ 1:
                    message.products.push(Product.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string timestamp */ 2:
                    message.timestamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PriceUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated product.Product products = 1; */
        for (let i = 0; i < message.products.length; i++)
            Product.internalBinaryWrite(message.products[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string timestamp = 2; */
        if (message.timestamp !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.PriceUpdate
 */
export const PriceUpdate = new PriceUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchStockAlertsRequest$Type extends MessageType<WatchStockAlertsRequest> {
    constructor() {
        super("product.WatchStockAlertsRequest", []);
    }
    create(value?: PartialMessage<WatchStockAlertsRequest>): WatchStockAlertsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<WatchStockAlertsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchStockAlertsRequest): WatchStockAlertsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchStockAlertsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.WatchStockAlertsRequest
 */
export const WatchStockAlertsRequest = new WatchStockAlertsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StockAlertUpdate$Type extends MessageType<StockAlertUpdate> {
    constructor() {
        super("product.StockAlertUpdate", [
            { no: 1, name: "alerts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => StockAlert },
            { no: 2, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StockAlertUpdate>): StockAlertUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.alerts = [];
        message.timestamp = "";
        if (value !== undefined)
            reflectionMergePartial<StockAlertUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StockAlertUpdate): StockAlertUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated product.StockAlert alerts */ 1:
                    message.alerts.push(StockAlert.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string timestamp */ 2:
                    message.timestamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StockAlertUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated product.StockAlert alerts = 1; */
        for (let i = 0; i < message.alerts.length; i++)
            StockAlert.internalBinaryWrite(message.alerts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string timestamp = 2; */
        if (message.timestamp !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.StockAlertUpdate
 */
export const StockAlertUpdate = new StockAlertUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchTopProductsByPriceRequest$Type extends MessageType<WatchTopProductsByPriceRequest> {
    constructor() {
        super("product.WatchTopProductsByPriceRequest", [
            { no: 1, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<WatchTopProductsByPriceRequest>): WatchTopProductsByPriceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<WatchTopProductsByPriceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchTopProductsByPriceRequest): WatchTopProductsByPriceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 limit */ 1:
                    message.limit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchTopProductsByPriceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 limit = 1; */
        if (message.limit !== 0)
            writer.tag(1, WireType.Varint).int32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.WatchTopProductsByPriceRequest
 */
export const WatchTopProductsByPriceRequest = new WatchTopProductsByPriceRequest$Type();
/**
 * @generated ServiceType for protobuf service product.ProductService
 */
export const ProductService = new ServiceType("product.ProductService", [
    { name: "WatchStockAlerts", serverStreaming: true, options: {}, I: WatchStockAlertsRequest, O: StockAlertUpdate },
    { name: "WatchTopProductsByPrice", serverStreaming: true, options: {}, I: WatchTopProductsByPriceRequest, O: PriceUpdate }
]);
