// @generated by protobuf-ts 2.11.1 with parameter client_grpc1,generate_dependencies
// @generated from protobuf file "warehouse.proto" (package "warehouse", syntax proto3)
// tslint:disable
import { WarehouseService } from "./warehouse";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { WarehouseUpdate } from "./warehouse";
import type { WatchWarehousesRequest } from "./warehouse";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service warehouse.WarehouseService
 */
export interface IWarehouseServiceClient {
    /**
     * @generated from protobuf rpc: WatchWarehouses
     */
    watchWarehouses(input: WatchWarehousesRequest, metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<WarehouseUpdate>;
    watchWarehouses(input: WatchWarehousesRequest, options?: grpc.CallOptions): grpc.ClientReadableStream<WarehouseUpdate>;
}
/**
 * @generated from protobuf service warehouse.WarehouseService
 */
export class WarehouseServiceClient extends grpc.Client implements IWarehouseServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: WatchWarehouses
     */
    watchWarehouses(input: WatchWarehousesRequest, metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientReadableStream<WarehouseUpdate> {
        const method = WarehouseService.methods[0];
        return this.makeServerStreamRequest<WatchWarehousesRequest, WarehouseUpdate>(`/${WarehouseService.typeName}/${method.name}`, (value: WatchWarehousesRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): WarehouseUpdate => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), options);
    }
}
