// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "warehouse.proto" (package "warehouse", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message warehouse.Warehouse
 */
export interface Warehouse {
    /**
     * @generated from protobuf field: string uuid = 1
     */
    uuid: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string address = 3
     */
    address: string;
    /**
     * @generated from protobuf field: string city = 4
     */
    city: string;
    /**
     * @generated from protobuf field: string state = 5
     */
    state: string;
    /**
     * @generated from protobuf field: string country = 6
     */
    country: string;
    /**
     * @generated from protobuf field: string postal_code = 7
     */
    postalCode: string;
    /**
     * @generated from protobuf field: string manager_name = 8
     */
    managerName: string;
    /**
     * @generated from protobuf field: string manager_email = 9
     */
    managerEmail: string;
    /**
     * @generated from protobuf field: string manager_phone = 10
     */
    managerPhone: string;
    /**
     * @generated from protobuf field: int32 capacity = 11
     */
    capacity: number;
    /**
     * @generated from protobuf field: bool is_active = 12
     */
    isActive: boolean;
    /**
     * @generated from protobuf field: string created_at = 13
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 14
     */
    updatedAt: string;
}
/**
 * @generated from protobuf message warehouse.WarehouseWithMetrics
 */
export interface WarehouseWithMetrics {
    /**
     * @generated from protobuf field: warehouse.Warehouse warehouse = 1
     */
    warehouse?: Warehouse;
    /**
     * @generated from protobuf field: int32 total_stock = 2
     */
    totalStock: number;
    /**
     * @generated from protobuf field: double utilization = 3
     */
    utilization: number;
}
/**
 * @generated from protobuf message warehouse.WatchWarehousesRequest
 */
export interface WatchWarehousesRequest {
    /**
     * @generated from protobuf field: bool include_metrics = 1
     */
    includeMetrics: boolean;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number; // 0 means no limit
}
/**
 * @generated from protobuf message warehouse.WarehouseUpdate
 */
export interface WarehouseUpdate {
    /**
     * @generated from protobuf field: repeated warehouse.WarehouseWithMetrics warehouses = 1
     */
    warehouses: WarehouseWithMetrics[];
    /**
     * @generated from protobuf field: string timestamp = 2
     */
    timestamp: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Warehouse$Type extends MessageType<Warehouse> {
    constructor() {
        super("warehouse.Warehouse", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "city", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "country", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "postal_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "manager_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "manager_email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "manager_phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Warehouse>): Warehouse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuid = "";
        message.name = "";
        message.address = "";
        message.city = "";
        message.state = "";
        message.country = "";
        message.postalCode = "";
        message.managerName = "";
        message.managerEmail = "";
        message.managerPhone = "";
        message.capacity = 0;
        message.isActive = false;
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<Warehouse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Warehouse): Warehouse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string address */ 3:
                    message.address = reader.string();
                    break;
                case /* string city */ 4:
                    message.city = reader.string();
                    break;
                case /* string state */ 5:
                    message.state = reader.string();
                    break;
                case /* string country */ 6:
                    message.country = reader.string();
                    break;
                case /* string postal_code */ 7:
                    message.postalCode = reader.string();
                    break;
                case /* string manager_name */ 8:
                    message.managerName = reader.string();
                    break;
                case /* string manager_email */ 9:
                    message.managerEmail = reader.string();
                    break;
                case /* string manager_phone */ 10:
                    message.managerPhone = reader.string();
                    break;
                case /* int32 capacity */ 11:
                    message.capacity = reader.int32();
                    break;
                case /* bool is_active */ 12:
                    message.isActive = reader.bool();
                    break;
                case /* string created_at */ 13:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 14:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Warehouse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string address = 3; */
        if (message.address !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.address);
        /* string city = 4; */
        if (message.city !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.city);
        /* string state = 5; */
        if (message.state !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.state);
        /* string country = 6; */
        if (message.country !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.country);
        /* string postal_code = 7; */
        if (message.postalCode !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.postalCode);
        /* string manager_name = 8; */
        if (message.managerName !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.managerName);
        /* string manager_email = 9; */
        if (message.managerEmail !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.managerEmail);
        /* string manager_phone = 10; */
        if (message.managerPhone !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.managerPhone);
        /* int32 capacity = 11; */
        if (message.capacity !== 0)
            writer.tag(11, WireType.Varint).int32(message.capacity);
        /* bool is_active = 12; */
        if (message.isActive !== false)
            writer.tag(12, WireType.Varint).bool(message.isActive);
        /* string created_at = 13; */
        if (message.createdAt !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 14; */
        if (message.updatedAt !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message warehouse.Warehouse
 */
export const Warehouse = new Warehouse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WarehouseWithMetrics$Type extends MessageType<WarehouseWithMetrics> {
    constructor() {
        super("warehouse.WarehouseWithMetrics", [
            { no: 1, name: "warehouse", kind: "message", T: () => Warehouse },
            { no: 2, name: "total_stock", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "utilization", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<WarehouseWithMetrics>): WarehouseWithMetrics {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.totalStock = 0;
        message.utilization = 0;
        if (value !== undefined)
            reflectionMergePartial<WarehouseWithMetrics>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WarehouseWithMetrics): WarehouseWithMetrics {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* warehouse.Warehouse warehouse */ 1:
                    message.warehouse = Warehouse.internalBinaryRead(reader, reader.uint32(), options, message.warehouse);
                    break;
                case /* int32 total_stock */ 2:
                    message.totalStock = reader.int32();
                    break;
                case /* double utilization */ 3:
                    message.utilization = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WarehouseWithMetrics, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* warehouse.Warehouse warehouse = 1; */
        if (message.warehouse)
            Warehouse.internalBinaryWrite(message.warehouse, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 total_stock = 2; */
        if (message.totalStock !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalStock);
        /* double utilization = 3; */
        if (message.utilization !== 0)
            writer.tag(3, WireType.Bit64).double(message.utilization);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message warehouse.WarehouseWithMetrics
 */
export const WarehouseWithMetrics = new WarehouseWithMetrics$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchWarehousesRequest$Type extends MessageType<WatchWarehousesRequest> {
    constructor() {
        super("warehouse.WatchWarehousesRequest", [
            { no: 1, name: "include_metrics", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<WatchWarehousesRequest>): WatchWarehousesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.includeMetrics = false;
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<WatchWarehousesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchWarehousesRequest): WatchWarehousesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool include_metrics */ 1:
                    message.includeMetrics = reader.bool();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchWarehousesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool include_metrics = 1; */
        if (message.includeMetrics !== false)
            writer.tag(1, WireType.Varint).bool(message.includeMetrics);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message warehouse.WatchWarehousesRequest
 */
export const WatchWarehousesRequest = new WatchWarehousesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WarehouseUpdate$Type extends MessageType<WarehouseUpdate> {
    constructor() {
        super("warehouse.WarehouseUpdate", [
            { no: 1, name: "warehouses", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WarehouseWithMetrics },
            { no: 2, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WarehouseUpdate>): WarehouseUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.warehouses = [];
        message.timestamp = "";
        if (value !== undefined)
            reflectionMergePartial<WarehouseUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WarehouseUpdate): WarehouseUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated warehouse.WarehouseWithMetrics warehouses */ 1:
                    message.warehouses.push(WarehouseWithMetrics.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string timestamp */ 2:
                    message.timestamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WarehouseUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated warehouse.WarehouseWithMetrics warehouses = 1; */
        for (let i = 0; i < message.warehouses.length; i++)
            WarehouseWithMetrics.internalBinaryWrite(message.warehouses[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string timestamp = 2; */
        if (message.timestamp !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message warehouse.WarehouseUpdate
 */
export const WarehouseUpdate = new WarehouseUpdate$Type();
/**
 * @generated ServiceType for protobuf service warehouse.WarehouseService
 */
export const WarehouseService = new ServiceType("warehouse.WarehouseService", [
    { name: "WatchWarehouses", serverStreaming: true, options: {}, I: WatchWarehousesRequest, O: WarehouseUpdate }
]);
