// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "warehouse.proto" (package "warehouse", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WarehouseService } from "./warehouse";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { WarehouseUpdate } from "./warehouse";
import type { WatchWarehousesRequest } from "./warehouse";
import type { WatchWarehouseCountRequest } from "./warehouse";
import type { WarehouseCountUpdate } from "./warehouse";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service warehouse.WarehouseService
 */
export interface IWarehouseServiceClient {
    /**
     * @generated from protobuf rpc: WatchWarehouses
     */
    watchWarehouses(input: WatchWarehousesRequest, options?: RpcOptions): ServerStreamingCall<WatchWarehousesRequest, WarehouseUpdate>;
    /**
     * @generated from protobuf rpc: WatchWarehouseCount
     */
    watchWarehouseCount(input: WatchWarehouseCountRequest, options?: RpcOptions): ServerStreamingCall<WatchWarehouseCountRequest, WarehouseCountUpdate>;
}
/**
 * @generated from protobuf service warehouse.WarehouseService
 */
export class WarehouseServiceClient implements IWarehouseServiceClient, ServiceInfo {
    typeName = WarehouseService.typeName;
    methods = WarehouseService.methods;
    options = WarehouseService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: WatchWarehouses
     */
    watchWarehouses(input: WatchWarehousesRequest, options?: RpcOptions): ServerStreamingCall<WatchWarehousesRequest, WarehouseUpdate> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchWarehousesRequest, WarehouseUpdate>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WatchWarehouseCount
     */
    watchWarehouseCount(input: WatchWarehouseCountRequest, options?: RpcOptions): ServerStreamingCall<WatchWarehouseCountRequest, WarehouseCountUpdate> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchWarehouseCountRequest, WarehouseCountUpdate>("serverStreaming", this._transport, method, opt, input);
    }
}
