// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/warehouse/warehouse.proto

package warehouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	ManagerName   string                 `protobuf:"bytes,8,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`
	ManagerEmail  string                 `protobuf:"bytes,9,opt,name=manager_email,json=managerEmail,proto3" json:"manager_email,omitempty"`
	ManagerPhone  string                 `protobuf:"bytes,10,opt,name=manager_phone,json=managerPhone,proto3" json:"manager_phone,omitempty"`
	Capacity      int32                  `protobuf:"varint,11,opt,name=capacity,proto3" json:"capacity,omitempty"`
	IsActive      bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *Warehouse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Warehouse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Warehouse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Warehouse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Warehouse) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Warehouse) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

func (x *Warehouse) GetManagerEmail() string {
	if x != nil {
		return x.ManagerEmail
	}
	return ""
}

func (x *Warehouse) GetManagerPhone() string {
	if x != nil {
		return x.ManagerPhone
	}
	return ""
}

func (x *Warehouse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Warehouse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Warehouse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Warehouse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WarehouseWithMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	TotalStock    int32                  `protobuf:"varint,2,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	Utilization   float64                `protobuf:"fixed64,3,opt,name=utilization,proto3" json:"utilization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseWithMetrics) Reset() {
	*x = WarehouseWithMetrics{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseWithMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseWithMetrics) ProtoMessage() {}

func (x *WarehouseWithMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseWithMetrics.ProtoReflect.Descriptor instead.
func (*WarehouseWithMetrics) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *WarehouseWithMetrics) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

func (x *WarehouseWithMetrics) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *WarehouseWithMetrics) GetUtilization() float64 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

type WatchWarehousesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetrics bool                   `protobuf:"varint,1,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 0 means no limit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchWarehousesRequest) Reset() {
	*x = WatchWarehousesRequest{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWarehousesRequest) ProtoMessage() {}

func (x *WatchWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWarehousesRequest.ProtoReflect.Descriptor instead.
func (*WatchWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *WatchWarehousesRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

func (x *WatchWarehousesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WarehouseUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Warehouses    []*WarehouseWithMetrics `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	Timestamp     string                  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseUpdate) Reset() {
	*x = WarehouseUpdate{}
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseUpdate) ProtoMessage() {}

func (x *WarehouseUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseUpdate.ProtoReflect.Descriptor instead.
func (*WarehouseUpdate) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *WarehouseUpdate) GetWarehouses() []*WarehouseWithMetrics {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

func (x *WarehouseUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_warehouse_warehouse_proto protoreflect.FileDescriptor

const file_proto_warehouse_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/warehouse/warehouse.proto\x12\twarehouse\"\x96\x03\n" +
	"\tWarehouse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fmanager_name\x18\b \x01(\tR\vmanagerName\x12#\n" +
	"\rmanager_email\x18\t \x01(\tR\fmanagerEmail\x12#\n" +
	"\rmanager_phone\x18\n" +
	" \x01(\tR\fmanagerPhone\x12\x1a\n" +
	"\bcapacity\x18\v \x01(\x05R\bcapacity\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\x8d\x01\n" +
	"\x14WarehouseWithMetrics\x122\n" +
	"\twarehouse\x18\x01 \x01(\v2\x14.warehouse.WarehouseR\twarehouse\x12\x1f\n" +
	"\vtotal_stock\x18\x02 \x01(\x05R\n" +
	"totalStock\x12 \n" +
	"\vutilization\x18\x03 \x01(\x01R\vutilization\"W\n" +
	"\x16WatchWarehousesRequest\x12'\n" +
	"\x0finclude_metrics\x18\x01 \x01(\bR\x0eincludeMetrics\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"p\n" +
	"\x0fWarehouseUpdate\x12?\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x1f.warehouse.WarehouseWithMetricsR\n" +
	"warehouses\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp2f\n" +
	"\x10WarehouseService\x12R\n" +
	"\x0fWatchWarehouses\x12!.warehouse.WatchWarehousesRequest\x1a\x1a.warehouse.WarehouseUpdate0\x01B\x11Z\x0fproto/warehouseb\x06proto3"

var (
	file_proto_warehouse_warehouse_proto_rawDescOnce sync.Once
	file_proto_warehouse_warehouse_proto_rawDescData []byte
)

func file_proto_warehouse_warehouse_proto_rawDescGZIP() []byte {
	file_proto_warehouse_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_warehouse_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_warehouse_warehouse_proto_rawDesc), len(file_proto_warehouse_warehouse_proto_rawDesc)))
	})
	return file_proto_warehouse_warehouse_proto_rawDescData
}

var file_proto_warehouse_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_warehouse_warehouse_proto_goTypes = []any{
	(*Warehouse)(nil),              // 0: warehouse.Warehouse
	(*WarehouseWithMetrics)(nil),   // 1: warehouse.WarehouseWithMetrics
	(*WatchWarehousesRequest)(nil), // 2: warehouse.WatchWarehousesRequest
	(*WarehouseUpdate)(nil),        // 3: warehouse.WarehouseUpdate
}
var file_proto_warehouse_warehouse_proto_depIdxs = []int32{
	0, // 0: warehouse.WarehouseWithMetrics.warehouse:type_name -> warehouse.Warehouse
	1, // 1: warehouse.WarehouseUpdate.warehouses:type_name -> warehouse.WarehouseWithMetrics
	2, // 2: warehouse.WarehouseService.WatchWarehouses:input_type -> warehouse.WatchWarehousesRequest
	3, // 3: warehouse.WarehouseService.WatchWarehouses:output_type -> warehouse.WarehouseUpdate
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_warehouse_warehouse_proto_init() }
func file_proto_warehouse_warehouse_proto_init() {
	if File_proto_warehouse_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_warehouse_warehouse_proto_rawDesc), len(file_proto_warehouse_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_warehouse_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_warehouse_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_warehouse_warehouse_proto_msgTypes,
	}.Build()
	File_proto_warehouse_warehouse_proto = out.File
	file_proto_warehouse_warehouse_proto_goTypes = nil
	file_proto_warehouse_warehouse_proto_depIdxs = nil
}
